### ISSUE TITLE
Feature request: isDirty

### ISSUE THREAD

**Issue by Truffula** [rwjblue/git-repo-info#15]
Great library! It would be handy to also report if the current branch has uncommitted changes.

Cheers!

**Comment by rwjblue** [comment]
I'm not sure how to detect this without shelling out (I don't think the .git internal file structure has dirty information).

One of the goals of this library is to avoid shelling out to the 'git' CLI...

**Comment by Truffula** [comment]
Ah, fair enough! Thanks anyway!
