### ISSUE TITLE
TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by archit** [rwjblue/git-repo-info#23]
This is a duplicate of #14  Not entirely sure how he got it working in there, through some magical reason.

I'm actually experiencing this problem, as part of my ember-cli-deploy upgrade for an ember-cli project. So I tested it by throwing together a small nodejs script which uses just `git-repo-info`.

``` javascript
var gitRepoInfo = require('git-repo-info');
var path = gitRepoInfo._findRepo();
var info = gitRepoInfo(path);

console.log(info);
```

The output from running that is

``` bash
{ sha: null,
  abbreviatedSha: null,
  branch: null,
  tag: null,
  root: '/Users/archit/Projects/<project-name>' }
```

This results in `ember-cli-deploy-revision-data` breaking, atleast in my workflow.

Running this with `node v6.3.0` and `npm v3.10.3` and `git version 2.3.2 (Apple Git-55)` on `Mac OS X El Capitan version 10.11.6`

**Comment by archit** [comment]
Ok some good news. I tested this with `node v4.5.0` and `git version 1.9.1` on `Ubuntu 14.04.5 LTS` and I don't see this error anymore. I'll run some tests to see if its `git` or `node` thats causing the issues.

**Comment by hjdivad** [comment]
@archit were you able to create a minimal reproducible test case?

**Comment by archit** [comment]
@hjdivad yeah, so these are the tests I did.

I upgraded my git to 2.x on (specifically `2.10.1`) on `Ubuntu 14.04.5 LTS` and the tests succeeded.

And I downgraded my nodejs to `v4.4.7` on `macOS Sierra` with `git version 2.8.4 (Apple Git-73)`, and the test failed.

**Comment by archit** [comment]
@hjdivad so it turns out, that this behavior is due to git submodules. The reason was that on my macOS laptop environment, I had a very old git submodule structure for my repositories. On my Ubuntu it wasn't the case. The git-submodule structure was what was causing the issue with the weird behavior. Not the fact that I was on macOS v/s Ubuntu.

**Comment by hjdivad** [comment]
@archit okay yes I vaguely remember that the format of submodules within `.git` changed at some point.

So to confirm you're not seeing this error on a fresh checkout of a repo with submodules on a modern version of git right?  Assuming that @rwjblue does not want to add support for old git submodule layouts (and I don't see any reason to) can this issue be closed?

**Comment by archit** [comment]
@hjdivad yes, the issue goes away when I re-`git-checkout` the project. we can close this issue.
