### ISSUE TITLE
Unexpected behaviour when GIT branches contains slash

### ISSUE THREAD

**Issue by mrjackdavis** [rwjblue/git-repo-info#3]
If the current GIT branch contains a `/`, then `getRepoInfo().branch` only returns what's after the slash.
### Example

Given the current GIT branch is `feature/amazingthing`

 `getRepoInfo().branch === 'amazingthing'`

**Comment by AKPWebDesign** [comment]
I need this feature working properly, so I went ahead and created a pull request for it.

**Comment by mrjackdavis** [comment]
@AKPWebDesign you're awesome! I ended up using `git-tools` instead. I might come back to this package if your PR gets merged

**Comment by AKPWebDesign** [comment]
I looked at `git-tools` for a few minutes, but decided that this was simpler than changing my current code to use callbacks. :stuck_out_tongue:

**Comment by mrjackdavis** [comment]
Haha fair enough
