### ISSUE TITLE
Deterministic findTag

### ISSUE THREAD

**Issue by jrowlingson** [rwjblue/git-repo-info#32]
https://github.com/rwjblue/git-repo-info/blob/c71c155bddb02e6540c26e4a276d600d199b83fe/index.js#L141-L142

When multiple tags are referencing the same commit the returned tag is dependent on whether it is packed or loose. Currently, the sort order is packed then loose. Each should be then alpha sorted (though readdir does not guarantee this).

I am thinking a manual sort of both loose and packed tags should do the trick.

**Comment by rwjblue** [comment]
Agreed.
