### ISSUE TITLE
How to get git url ?

### ISSUE THREAD

**Issue by ycjcl868** [rwjblue/git-repo-info#40]

**Comment by rwjblue** [comment]
I don’t think we currently have any APIs for gathering remote urls, is that what you are looking for?

I do think that would be a nice thing to have, and I believe we can parse it out of `.git/config` directly...

**Comment by ycjcl868** [comment]
Other git info may be parse if I parse `.git/config`, so the tool helped a little for me

**Comment by Glavin001** [comment]
@ycjcl868 What did you end up doing to get the git remote URL? Any sample code you'd like to share?

**Comment by joshbw** [comment]
@Glavin001 I admittedly don't have an exhaustive set of test cases, but from all of the repos I have synced from various places, the regex /url\s*=\s*(.*)\s*/ run on config seems to do it (with the url being in the capture group)
