### ISSUE TITLE
Commits with multiple parents cause findLastTag to check same commits multiple times

### ISSUE THREAD

**Issue by AndrejZbin** [rwjblue/git-repo-info#54]
Merge commits have two parents, one pointing to the last commit in merged branch and one pointing to the last commit in original branch. If there is no tag found in neither of them, findLastTag will iterate through all their ancestors twice until tag is found.

**Comment by hjdivad** [comment]
@AndrejZbin minor point, merge commits have 2 or more parents; we might as well have the code handle N parents rather than just 2.

But the overwhelmingly common case is for merge commits to have exactly 2 parents.
