### ISSUE TITLE
Finding repo root

### ISSUE THREAD

**Issue by dominykas** [rwjblue/git-repo-info#7]
I need to find the root folder of a repository. There's a handy `_findRepo` exported, but I assume it's "private" and might change and it also returns a path with `.git` appended.

Would you accept a PR that exposes the root folder (without `.git`) as `info.root` returned by `getRepoInfo()`?

**Comment by rwjblue** [comment]
Yes, sounds good. I'd happily accept a PR with tests covering the various edge cases...

**Comment by rwjblue** [comment]
@dominykas - Ping?

**Comment by dominykas** [comment]
Oh, totally forgot about this. Will get onto it some time next week :)
