### ISSUE TITLE
Async version

### ISSUE THREAD

**Issue by Lesterpig** [rwjblue/git-repo-info#8]
Thank you for this module, it's pretty convenient :)

It could be interesting to build an async version of this module, for fastest and non-blocking operations.
What do you think about it?

I can work on this feature if needed.

**Comment by rwjblue** [comment]
I'm definitely open to reviewing/digging into an async version, but I'm not certain it will actually be more performant. Let me know if you are still interested in digging into it...

**Comment by Lesterpig** [comment]
Hi! It's been quite a long time, and I don't think this issue is still relevant (at least for me).
Feel free to close it if you want :smiley:

**Comment by rwjblue** [comment]
OK, thank you for the issue (and I am really sorry for not getting back to you in a timely fashion).

I'm going to close for now, happy to have someone pick this up in the future though...
